export const notifications = [
    {
        person_name: 'Mark Webber',
        person_image: '/images/avatar-mark-webber.webp',
        action_type: 'POST-REACTION',
        action_message: 'reacted to your recent post',
        related_element: 'My first tournament today!',
        minutes_ago: '1m ago',
        related_pic: null,
        unread: true,
    },
    {
        person_name: 'Angela Gray',
        person_image: '/images/avatar-angela-gray.webp',
        action_type: 'FOLLOWING',
        action_message: 'followed you',
        related_element: null,
        minutes_ago: '5m ago',
        related_pic: null,
        unread: true,
    },
    {
        person_name: 'Jacob Thompson',
        person_image: '/images/avatar-jacob-thompson.webp',
        action_type: 'JOINED-GROUP',
        action_message: 'has joined your group',
        related_element: 'Chess Club',
        minutes_ago: '1 day ago',
        related_pic: null,
        unread: true,
    },
    {
        person_name: 'Rizky Hasanuddin',
        person_image: '/images/avatar-rizky-hasanuddin.webp',
        action_type: 'PRIVATE-MESSAGE',
        action_message: 'sent you a private message',
        minutes_ago: '5 days ago',
        message: `Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and
        I'm already having lots of fun and improving my game.`,
        related_pic: null,
        unread: false,
    },
    {
        person_name: 'Kimberly Smith',
        person_image: '/images/avatar-kimberly-smith.webp',
        action_type: 'COMMENTED-PICTURE',
        action_message: 'commented on your picture',
        minutes_ago: '1 week ago',
        related_pic: '/images/image-chess.webp',
        unread: false,
    },
    {
        person_name: 'Nathan Peterson',
        person_image: '/images/avatar-nathan-peterson.webp',
        action_type: 'POST-REACTION',
        action_message: 'reacted to your recent post',
        minutes_ago: '1 week ago',
        related_element: '5 end-game strategies to increase your win rate',
        related_pic: null,
        unread: false,
    },
    {
        person_name: 'Anna Kim',
        person_image: '/images/avatar-anna-kim.webp',
        action_type: 'LEAVE-GROUP',
        action_message: 'left the group',
        minutes_ago: '2 weeks ago',
        related_element: 'Chess Club',
        related_pic: null,
        unread: false,
    },
]